import { HomePage, HomeViewModel } from "home/index.slint";
import { MenuPage, MenuViewModel } from "menu/index.slint";
import { PageRouter, PageRouteTable } from "../common/route.slint";
import { WeatherPage, WeatherViewModel } from "weather/index.slint";

export component RouteView inherits Rectangle {
    boot-page := Rectangle {
        visible: PageRouter.current-page == PageRouteTable.boot;
        Text {
            text: "原神，启动！";
        }
    }

    home-page := HomePage {
        visible: PageRouter.current-page == PageRouteTable.home;
        width: 100%;
        height: 100%;
    }

    menu-page := MenuPage {
        visible: PageRouter.current-page == PageRouteTable.menu;
        width: 100%;
        height: 100%;
    }

    weather-page := WeatherPage {
        visible: PageRouter.current-page == PageRouteTable.weather;
        width: 100%;
        height: 100%;
    }
}

export { 
    HomeViewModel, 
    MenuViewModel,
    WeatherViewModel
}