import { Button, ScrollView } from "std-widgets.slint";
import { StringListView } from "../../components/string-listview.slint";

export global MusicPageViewModel {
    in property <[string]> music-list;
    in-out property <int> select-id;
}

export component MusicPage inherits Rectangle {
    width: 240px;
    height: 240px;
    background: black;
    
    if MusicPageViewModel.music-list.length == 0: Text {
        text: "No music";
        font-size: 30px;
        color: white;
    }

    if MusicPageViewModel.music-list.length > 0: StringListView {
        string-list: MusicPageViewModel.music-list;
        select-id: MusicPageViewModel.select-id;
    }
}
