export struct MusicItemInfo {
    name: string,
    path: string,
}

export component MusicPage inherits Rectangle {
    in property <string> note;
    in property <float> percent;

    property <[MusicItemInfo]> music-list: [
        { name: "奥摩斯港", path: "Port_Ormos.mid" },
        { name: "瑶瑶PV曲", path: "Yaoyao_Character_Demo.mid" },
        { name: "雷电将军", path: "Raiden_Shogun_Judgment_of_Euthymia__Yu-Peng_Chen.mid" },
        { name: "雪山", path: "Dragonspine_Song_No._1_-_Yu-Peng_Chen.mid" },
        { name: "大梦的曲调", path: "Aranaras_Theme__HOYO-MiX_.mid" },
        { name: "罪人的终幕", path: "Sinners_Finale_Genshin_Impact.mid" },
        { name: "甘雨PV曲", path: "Ganyu_Radiant_Dreams_Genshin_Impact_-_Yu-peng_Chen.mid" },
        { name: "枫丹主题曲", path: "Fontaine__HOYO-MiX.mid"},
        { name: "可莉主题曲", path: "Klee.mid"},
        { name: "轻链", path: "Story_Teaser_La_vaguelette__Genshin_Impact.mid"},
        { name: "纳西妲PV曲", path: "Nahida_trailer.mid"},
        { name: "我不曾忘记", path: "我不曾忘记.mid"},
        { name: "绀田村", path: "Konda_Village_BGM_Morning_Genshin_Impact.mid"},
        { name: "宵宫PV", path: "Blossoms_of_Summer_Night__Dimeng_Yuan_from_Genshin_Impact.mid"},
        { name: "无虑无猜的岁月", path: "Genshin Impact - Innocent Age.mid"},
        { name: "MondstadtMedley", path: "Genshin_Impact_OST_-_Mondstadt_Medley_Piano.mid"},
    ];
    property <int> current-music-id: -1;

    // 播放指定音乐，返回是否加载成功
    callback play(MusicItemInfo) -> bool;
    callback enter();
    callback exit();

    // 当音乐播放完毕时
    // 返回条件为是否自动播放下一首
    public function on-play-done(info: MusicItemInfo) -> bool {
        debug("音乐播放完毕");
        if (play(music-list[Math.mod(current-music-id + 1, music-list.length)])) {
            debug("自动开始播放下一首");
        } else {
            debug("加载失败");
        }
        return true;
    }

    width: 240px;
    height: 240px;

    background: black;

    VerticalLayout {
        alignment: space-between;
        HorizontalLayout {
            alignment: center;
            Text {
                text: "正在演奏";
                font-size: 30px;
                color: white;
            }
        }

        HorizontalLayout {
            alignment: center;
            Image {
                width: 100px;
                height: 100px;
                source: @image-url("icons/music-cd.svg");
            }
        }
        HorizontalLayout {
            alignment: center;
            Text {
                text: current-music-id == -1 ? "按下按钮开始播放音乐" : music-list[current-music-id].name;
                font-size: 20px;
                color: white;
            }
        }
        Rectangle {
            width: percent * 240px;
            height: 5px;
            background: red;
            animate width {
                duration: 500ms;
                easing: ease-in-out;
            }
        }
    }

    // 进入页面
    public function on-enter() {
        enter();
    }

    // 单机按键切换音乐
    public function on-one-button-click() {
        current-music-id = Math.mod(current-music-id + 1, music-list.length);
        play(music-list[current-music-id]);
    }

    // 长按3秒退出
    public function on-one-button-long-pressed-holding(dur: duration) {
        if (dur > 3000ms) {
            exit();
        }
    }
}