[package]
name = "desktop-svc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-io = "0.6.1"
embedded-svc = "0.26.1"
reqwest = "0.11.22"
