import { Boot, BootState } from "boot.slint";
import { StandardListView, ListView, Button } from "std-widgets.slint";

export component BootTest inherits Window {
    preferred-height: 480px;
    VerticalLayout {
        boot := Boot {}
        ListView {
            for data in [
                {text: "Booting", state: BootState.Booting},
                {text: "Connecting", state: BootState.Connecting},
                {text: "BootFailed", state: BootState.BootFailed},
                {text: "BootSuccess", state: BootState.BootSuccess},
            ]: Button {
                text: data.text;
                clicked => {
                    boot.set-state(data.state);
                }
            }
        }
    }
}

