
component PerformanceMoniter inherits Rectangle {
    width: 240px;
    height: 240px;
    background: black;

    VerticalLayout {
        padding: 8px;
        Text {
            horizontal-alignment: center;
            text: "性能监控";
            font-size: 20px;
            color: white;
        }

        Rectangle {
            height: 10px;
        }

        Rectangle {
            height: 1px;
            background: white;
        }

        HorizontalLayout {
            VerticalLayout {
                alignment: center;
                Text {
                    horizontal-alignment: center;
                    text: "当前温度";
                    color: white;
                    font-size: 15px;
                }
                Text {
                    horizontal-alignment: center;
                    text: "0.00℃";
                    font-size: 15px;
                    color: white;
                }
            }
            Rectangle {
                width: 1px;
                background: gray;
            }
            VerticalLayout {
                alignment: center;
                Text {
                    horizontal-alignment: center;
                    text: "CPU";
                    font-size: 15px;
                    color: white;
                }
                Text {
                    horizontal-alignment: center;
                    text: "0.00%";
                    font-size: 15px;
                    color: white;
                }
            }
            Rectangle {
                width: 1px;
                background: gray;
            }
            VerticalLayout {
                alignment: center;
                Text {
                    horizontal-alignment: center;
                    text: "内存";
                    font-size: 15px;
                    color: white;
                }
                Text {
                    horizontal-alignment: center;
                    text: "0.00%";
                    font-size: 15px;
                    color: white;
                }
            }
        }
        Rectangle {
            height: 1px;
            background: white;
        }
        Rectangle {
            height: 10px;
        }
        Rectangle {
            border-color: gray;
            border-width: 1px;
            Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "CPU图表";
                font-size: 50px;
                color: white;
            }
        }
        Rectangle {
            border-color: gray;
            border-width: 1px;
            Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "内存图表";
                font-size: 50px;
                color: white;
            }
        }
    }
}