export global HomeIcons {
    out property <image> cloudy: @image-url("icons/cloudy.png");
    out property <image> sunny: @image-url("icons/sunny.png");
    out property <image> fog: @image-url("icons/fog.png");
    out property <image> rain: @image-url("icons/rain.png");
    out property <image> snow: @image-url("icons/snow.png");
    out property <image> hail: @image-url("icons/hail.png");
    out property <image> overcast: @image-url("icons/overcast.png");
    out property <image> sandstorm: @image-url("icons/sandstorm.png");
    out property <image> thunder: @image-url("icons/thunder.png");
    
    out property <image> water-level: @image-url("icons/water-level.svg");
    out property <image> thermometer: @image-url("icons/thermometer.svg");
}
