import { VerticalBox , StandardButton, Button, HorizontalBox, ListView, ScrollView} from "std-widgets.slint";
import { PageRouteTable } from "../../common/route.slint";
import { MenuIcons } from "assets/index.slint";

struct MenuItemEntry {
    title: string,
    page: PageRouteTable,
    icon: image,
}

export global MenuViewModel {
    out property <[MenuItemEntry]> entry-list: [
        {
            title: "Home",
            page: PageRouteTable.home,
            icon: MenuIcons.home,
        },
        {
            title: "Weather",
            page: PageRouteTable.weather,
            icon: MenuIcons.sun,
        },
        {
            title: "Music",
            page: PageRouteTable.music,
            icon: MenuIcons.home,
        },
    ];
    in-out property <int> current-id: 0;

    public function next() -> int {
        current-id = mod(current-id + entry-list.length + 1, entry-list.length);
        return current-id;
    }
}

component MenuItem inherits Rectangle {
    in property <MenuItemEntry> entry;

    width: 80px;
    height: 80px;

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                Image {
                    source: entry.icon;
                    width: 50px;
                    height: 50px;
                    colorize: goldenrod;
                }

                Rectangle {
                    height: 1px;
                }

                Text {
                    horizontal-alignment: center;
                    text: entry.title;
                    font-size: 20px;
                    color: white;
                }
            }
        }
    }
}

export component MenuPage inherits Rectangle {
    width: 240px;
    height: 280px;
    background: black;
    border-width: 2px;

    Rectangle {
        width: 80px;
        height: 80px;
        border-width: 2px;
        border-color: gray;
        x: mod(MenuViewModel.current-id, 3) * 80px;
        y: floor(mod(MenuViewModel.current-id, 9) / 3) * 80px;
        animate x, y {
            duration: 300ms;
            easing: ease-in;
        }
    }

    ScrollView {
        viewport-y: -(240px * floor(MenuViewModel.current-id / 9));
        for entry[id] in MenuViewModel.entry-list: Rectangle {
            width: 80px;
            height: 80px;
            x: mod(id, 3) * 80px;
            y: floor(id / 3) * 80px;
            MenuItem {
                entry: entry;
            }
        }
        animate viewport-y {
            duration: 500ms;
            easing: ease-in;
        }
    }
}

export component TestMenuPage inherits Rectangle {
    width: 240px;
    height: 240px;
    VerticalLayout {
        MenuPage { }
    }

    TouchArea {
        clicked => {
            MenuViewModel.next();
        }
    }
}
