import { VerticalBox , StandardButton, Button, HorizontalBox, ListView} from "std-widgets.slint";
import { PageRouteTable } from "../../common/route.slint";
import { MenuIcons } from "assets/index.slint";

struct MenuItemEntry {
    page: PageRouteTable,
    icon: image,
}

export global MenuViewModel {
    out property <[MenuItemEntry]> entry-list: [
        {
            page: PageRouteTable.home,
            icon: MenuIcons.home,
        },
        {
            page: PageRouteTable.weather,
            icon: MenuIcons.sun,
        },
        {
            page: PageRouteTable.music,
            icon: MenuIcons.home,
        },
        {
            page: PageRouteTable.home,
            icon: MenuIcons.home,
        },
    ];
    in-out property <int> current-id: 0;

    public function next() -> int {
        current-id = mod(current-id + entry-list.length + 1, entry-list.length);
        return current-id;
    }
}

component MenuItem inherits Rectangle {
    in property <MenuItemEntry> entry;

    width: 80px;
    height: 80px;
    function menu-item-name(p: PageRouteTable) -> string {
        if (p == PageRouteTable.home) {
            return "首页";
        }
        if (p == PageRouteTable.weather) {
            return "天气";
        }
        if (p == PageRouteTable.music) {
            return "音乐";
        }
        return "未知";
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                Image {
                    source: entry.icon;
                    width: 50px;
                    height: 50px;
                    colorize: goldenrod;
                }

                Rectangle {
                    height: 1px;
                }

                Text {
                    horizontal-alignment: center;
                    text: menu-item-name(entry.page);
                    font-size: 20px;
                    color: white;
                }
            }
        }
    }
}

export component MenuPage inherits Rectangle {
    width: 240px;
    height: 240px;
    background: black;
    border-width: 2px;

    for entry[id] in MenuViewModel.entry-list: Rectangle {
        width: 80px;
        height: 80px;
        border-width: 2px;
        border-color: id == MenuViewModel.current-id ? gray : black;
        x: mod(id, 3) * 80px;
        y: floor(id / 3) * 80px;
        MenuItem {
            entry: entry;
        }
    }
}

export component TestMenuPage inherits Rectangle {
    width: 240px;
    height: 240px;
    VerticalLayout {
        MenuPage { }
    }

    TouchArea {
        clicked => {
            MenuViewModel.next();
        }
    }
}
