export component ProjectorPage inherits Rectangle {
    in property <string> local-ip: "正在获取中...";
    in property <int> local-port: 8080;
    callback enter();
    callback exit();
    
    background: black;
    height: 240px;
    width: 240px;
    
    VerticalLayout {
        padding: 20px;
        alignment: space-between;
        Text {
            text: "等待客户端连接中...";
            color: red;
            font-size: 20px;
        }
    
        Text {
            text: "本机IP: \{local-ip}";
            color: yellow;
            font-size: 20px;
        }

        Text {
            text: "监听端口: \{local-port}";
            color: yellow;
            font-size: 20px;
        }

        Text {
            text: "长按3秒退出程序";
            color: red;
            font-size: 20px;
        }
    }


    // 进入页面
    public function on-enter() {
        enter();
    }

    // 长按3秒退出
    public function on-one-button-long-pressed-holding(dur: duration) {
        if (dur > 3000ms) {
            exit();
        }
    }
}