
export global AlertDialogViewModel {
    in-out property <percent> width: 80%;
    in-out property <percent> height: 80%;
    in-out property <string> text;
    in-out property <image> image;
    in-out property <bool> show;
}

export component AlertDialogView inherits Rectangle {
    visible: AlertDialogViewModel.show;
    Rectangle {
        border-color: gray;
        border-radius: 20px;
        border-width: 2px;
        background: black;
        width: AlertDialogViewModel.width;
        height: AlertDialogViewModel.height;
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                padding: 10px;
                alignment: center;
                Text {
                    text: AlertDialogViewModel.text;
                    font-size: 20px;
                    color: red;
                    wrap: word-wrap;
                }

                Image {
                    source: AlertDialogViewModel.image;
                }
            }
        }
    }
}