
export global PerformanceViewModel {
    in property <bool> is-show;
    in property <int> fps;
    in property <int> memory;
    in property <int> largest-free-block;
    in property <int> cpu;
}

export component PerformanceView inherits Rectangle {
    visible: PerformanceViewModel.is-show;
    in property <int> fps <=> PerformanceViewModel.fps;
    in property <int> memory <=> PerformanceViewModel.memory;
    in property <int> largest-free-block <=> PerformanceViewModel.largest-free-block;
    in property <int> cpu <=> PerformanceViewModel.cpu;

    VerticalLayout {
        alignment: start;
        HorizontalLayout {
            HorizontalLayout {
                alignment: start;
                Rectangle {
                    background: gray.with-alpha(0.5);
                    Text {
                        color: #ff2a00;
                        font-size: 20px;
                        text: "memory: \{memory}\n" + "free block: \{largest-free-block}";
                    }
                }
            }

            HorizontalLayout {
                alignment: end;
                Rectangle {
                    background: gray.with-alpha(0.5);
                    Text {
                        color: #ff2a00;
                        font-size: 20px;
                        text: "fps: \{fps}\n" + "cpu: \{cpu}";
                    }
                }
            }
        }
    }
}