import { PageRouteTable, PageRouter } from "common/route.slint";
import { RouteView, HomeViewModel, MenuViewModel, WeatherPageViewModel, MusicPageViewModel, BootPageViewModel } from "pages/index.slint";
import { TopView, AlertDialogViewModel, PerformanceViewModel, CanvasViewModel } from "topviews/index.slint";

export global OneButtenAdapter {
    callback pressed();
    callback release();
}

export component AppWindow inherits Window {
    width: 240px;
    height: 240px;

    TouchArea {
        pointer-event(e) => {
            if (e.button == PointerEventButton.left) {
                if (e.kind == PointerEventKind.down) {
                    OneButtenAdapter.pressed()
                } else if (e.kind == PointerEventKind.up) {
                    OneButtenAdapter.release()
                }
            }
        }
    }

    FocusScope {
        key-pressed(e) => {
            if (e.text == Key.Space) {
                OneButtenAdapter.pressed();
            }
            accept
        }
        key-released(e) => {
            OneButtenAdapter.release();
            accept
        }
    }

    TopView {
        z: 1;
        width: 100%;
        height: 100%;
    }

    RouteView {
        z: 0;
        width: 100%;
        height: 100%;
    }
}

export { 
    HomeViewModel,
    MenuViewModel,
    PageRouter,
    WeatherPageViewModel, 
    MusicPageViewModel,
    BootPageViewModel,
    AlertDialogViewModel, 
    PerformanceViewModel, 
    CanvasViewModel
}