import { VerticalBox , StandardButton, Button, HorizontalBox} from "std-widgets.slint";

export struct MenuItemEntry {
    id: string,
    name: string,
    icon: image,
}

component MenuItem inherits Rectangle {
    in property <MenuItemEntry> entry;
    width: 240px;
    height: 240px;
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                Image {
                    source: entry.icon;
                    width: 120px;
                    height: 120px;
                    colorize: goldenrod;
                }
                Rectangle { height: 10px; }
                Text {
                    horizontal-alignment: center;
                    text: entry.name;
                    font-size: 24px;
                    color: white;
                }
            }
        }
    }
}

export component Menu inherits Rectangle {
    width: 240px;
    height: 240px;
    background: black;
    border-width: 2px;
    
    callback on-entered(int, MenuItemEntry);

    in property <[MenuItemEntry]> entry-list;
    property <int> id: 0;

    public function next() {
        id = Math.mod(id+1, entry-list.length)
    }

    public function enter() {
        debug("Enter id: \{id}");
        on-entered(id, entry-list[id]);
    }

    HorizontalLayout {
        x: -id*parent.height;
        for entry in entry-list: MenuItem {
            entry: entry;
        }
        
        animate x {
            duration: 500ms;
            easing: ease-in-out;
        }
    }


}

component MenuTest inherits Window {
    width: 240px;
    height: 480px;

    VerticalLayout {
        menu := Menu {
            entry-list: [
                {
                    name: "Home",
                    icon: @image-url("home.svg"),
                },
                {
                    name: "Weather",
                    icon: @image-url("sun.svg"),
                },
                {
                    name: "Monitor",
                    icon: @image-url("electrocardiogram.svg"),
                },
                {
                    name: "Photo",
                    icon: @image-url("photograph.svg"),
                },
            ];
        }
        Button {
            text: "Next";
            clicked => {
                menu.next();
            }
        }
        Button {
            text: "Enter";
            clicked => {
                menu.enter();
            }
        }
    }
}