import { Boot } from "boot/boot.slint";
import { Home, HomeData, Location } from "home/home.slint";
import { Menu } from "menu/menu.slint";
import "./font/microsoft-yahei.ttf";
import { Button } from "std-widgets.slint";
import { Weather, WeatherLogic } from "home/weather/weather.slint";

export { Weather, WeatherLogic, Location }

export enum Page {
    Boot,
    Home,
    Menu,
}

component MultiPage inherits Rectangle {
    in-out property <HomeData> home-data;

    property <Page> current-page: Page.Boot;

    boot := Boot {
        visible: current-page == Page.Boot;
    }
    home := Home {
        visible: current-page == Page.Home;
        data: home-data;
    }
    menu := Menu {
        visible: current-page == Page.Menu;
        entry-list: [
            {
                id: "home",
                name: "首页",
                icon: @image-url("menu/home.svg"),
            },
            {
                id: "weather",
                name: "天气",
                icon: @image-url("menu/sun.svg"),
            },
            {
                id: "moniter",
                name: "性能监视器",
                icon: @image-url("menu/electrocardiogram.svg"),
            }
        ];
        on-entered(id, entry) => {
            if (entry.id == "home") {
                current-page = Page.Home;
            }
        }
    }

    public function boot() {
        current-page = Page.Boot;
        boot.boot();
    }

    public function goto-home() {
        current-page = Page.Home;
    }
    
    public function on-one-button-click() {
        if (current-page == Page.Home) {
            current-page = Page.Menu;
        } else if (current-page == Page.Menu) {
            menu.next();
        }

    }

    public function on-one-button-double-click() {
        if (current-page == Page.Menu) {
            menu.enter();
        }
    }
    
    public function on-one-button-long-pressed() {
        debug("on-one-button-long-pressed");
    }
}

export component AppWindow inherits Window {
    default-font-family: "Microsoft YaHei";
    width: 240px;
    height: 240px;
    
    in-out property <HomeData> home-data;

    m := MultiPage{
        home-data: home-data;
    }

    public function boot() {
        m.boot();
    }

    public function on-one-button-click() {
        m.on-one-button-click();
    }
    public function on-one-button-double-click() {
        m.on-one-button-double-click();
    }
    public function goto-home() {
        m.goto-home();
    }

}

component AppWindowTest inherits AppWindow {
    default-font-family: "Microsoft YaHei";
    width: 240px;
}