import { VerticalBox , StandardButton, Button, HorizontalBox} from "std-widgets.slint";

component MenuItem inherits Rectangle {
    in property <image> icon;
    in property <string> name;
    width: 240px;
    height: 240px;
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                Image {
                    source: icon;
                    width: 120px;
                    height: 120px;
                    colorize: goldenrod;
                }
                Rectangle { height: 10px; }
                Text {
                    horizontal-alignment: center;
                    text: name;
                    font-size: 24px;
                    color: white;
                }
            }
        }
    }
}
export component Menu inherits Rectangle {
    width: 240px;
    height: 240px;
    background: black;
    border-width: 2px;

    property <int> max-items: 3;
    property <int> id: 0;

    function normalize(id: int) -> int {
        if (id < 0) {
            return max-items + id;
        } else if (id >= max-items) {
            return id - max-items;
        } else {
            return id;
        }
    }

    public function next() {
        id = normalize(id+1);
    }

    public function enter() {
        debug("Enter id: \{id}");
    }

    HorizontalLayout {
        x: -normalize(id)*parent.height;
        MenuItem {
            name: "Home";
            icon: @image-url("menu/home.svg");
        }
        MenuItem {
            name: "Weather";
            icon: @image-url("menu/sun.svg");
        }
        MenuItem {
            name: "Monitor";
            icon: @image-url("menu/electrocardiogram.svg");
        }
        animate x {
            duration: 500ms;
            easing: ease-in-out;
        }
    }


}

component MenuTest inherits Window {
    width: 240px;
    height: 480px;

    VerticalLayout {
        menu := Menu {

        }
        Button {
            text: "Next";
            clicked => {
                menu.next();
            }
        }
        Button {
            text: "Enter";
            clicked => {
                menu.enter();
            }
        }
    }
}