[package]
name = "slint-app"
version = "0.1.0"
edition = "2021"

[dependencies]
# slint = { version = "1.0.0", default-features = false, features = ["compat-1-0", "unsafe-single-threaded"] }
slint ={ version = "1.3.0"}
log = { version = "0.4.17" }
time = "0.3.25"
embedded-svc = "0.26.2"
euclid = "0.22.9" # slint will build error if don't have this
embedded-graphics-group = { path = "../libs/embedded-graphics-group" }
embedded-graphics = "0.8.1"
embedded-tone = { path = "../libs/embedded-tone" }

[build-dependencies]
slint-build = { version = "1.0.0" }
