[package]
name = "slint-app"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.0.0" }
log = { version = "0.4.17" }
time = "0.3.25"
embedded-svc = "0.26.2"
force-send-sync = "1.1.0"
tinytga = "0.5.0"


[build-dependencies]
slint-build = { version = "1.0.0" }
