[build]
target = "riscv32imc-esp-espidf"
# target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --partition-table=partitions.csv -s=4mb" # Select this runner for espflash v2.x.x
rustflags = [
    "--cfg","espidf_time64", 
    "-C","default-linker-libraries",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# MCU="esp32s3"
ESP_IDF_VERSION = "v5.1.3"
ESP_IDF_PATH_ISSUES = 'warn'