import { HomePage, HomeViewModel } from "home/index.slint";
import { MenuPage, MenuViewModel } from "menu/index.slint";
import { PageRouter, PageRouteTable } from "../common/route.slint";

export component RouteView inherits Rectangle {
    home-page := HomePage {
        visible: PageRouter.current-page == PageRouteTable.home;
    }

    menu-page := MenuPage {
        visible: PageRouter.current-page == PageRouteTable.menu;
    }
}

export { 
    HomeViewModel, 
    MenuViewModel
}