[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
base64 = "0.22.1"
time = { version = "0.3.36", features = [
    "parsing",
    "serde",
    "macros",
    "formatting",
] }
