name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build app for desktop
        run: |
          sudo apt update
          sudo apt install libudev-dev libasound2-dev libsdl2-dev
          cargo install ldproxy
          git submodule update --init
          cd app/desktop-impl && cargo build && cd -
          cd app/esp32c3-impl && cargo build && cd -
          cd server && cargo build && cd -